"""Sense: local-first context and capability evaluation for physical machines."""

from __future__ import annotations

from sense_ai.errors import (
    InvalidRuleError,
    MissingEvidenceError,
    PeaqConfigurationError,
    PeaqNetworkError,
    SchemaValidationError,
    SenseError,
    SerializationError,
    UnknownCapabilityError,
    UnsupportedPeaqFlowError,
)
from sense_ai.events import (
    CapabilityEvaluatedEvent,
    EventBus,
    EventHandler,
    EventType,
    RawEvent,
    SnapshotCreatedEvent,
    TransitionDetectedEvent,
)
from sense_ai.model import (
    CapabilitySpec,
    CapabilityStatus,
    ContextMachine,
    ContextSnapshot,
    ContextTransition,
    TelemetryObservation,
)
from sense_ai.model.capability import capability
from sense_ai.model.result import CapabilityResult, ConstraintResult
from sense_ai.rules import (
    ALL,
    ANY,
    NONE_OF,
    NOT,
    ONLY_ONE,
    Constraint,
    ConstraintOutcome,
    Equals,
    Exists,
    Fresh,
    Gt,
    Gte,
    In,
    Lt,
    Lte,
    equals,
    exists,
    fresh,
    gt,
    gte,
    in_,
    lt,
    lte,
)
from sense_ai.trust import (
    EvidenceQualityDimension,
    EvidenceQualityReport,
    TrustDimension,
    TrustReport,
    compute_evidence_quality,
    compute_trust_report,
)

__all__ = [
    "ALL",
    "ANY",
    "NONE_OF",
    "NOT",
    "ONLY_ONE",
    "CapabilityEvaluatedEvent",
    "CapabilityResult",
    "CapabilitySpec",
    "CapabilityStatus",
    "Constraint",
    "ConstraintOutcome",
    "ConstraintResult",
    "ContextMachine",
    "ContextSnapshot",
    "ContextTransition",
    "Equals",
    "EventBus",
    "EventHandler",
    "EventType",
    "EvidenceQualityDimension",
    "EvidenceQualityReport",
    "Exists",
    "Fresh",
    "Gt",
    "Gte",
    "In",
    "InvalidRuleError",
    "Lt",
    "Lte",
    "MissingEvidenceError",
    "PeaqConfigurationError",
    "PeaqNetworkError",
    "RawEvent",
    "SchemaValidationError",
    "SenseError",
    "SerializationError",
    "SnapshotCreatedEvent",
    "TelemetryObservation",
    "TransitionDetectedEvent",
    "TrustDimension",
    "TrustReport",
    "UnknownCapabilityError",
    "UnsupportedPeaqFlowError",
    "capability",
    "compute_evidence_quality",
    "compute_trust_report",
    "equals",
    "exists",
    "fresh",
    "gt",
    "gte",
    "in_",
    "lt",
    "lte",
]

__version__ = "0.2.0"
